name: uniun
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

global_options:
  freezed:freezed:
    runs_before:
      - isar_generator:isar_generator

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  hydrated_bloc: ^9.1.3
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  dio: ^5.4.0
  hive: ^2.2.3
  go_router: ^13.0.1
  adaptive_theme: ^3.5.0
  equatable: ^2.0.5
  markdown_editable_textinput:
    git:
      url: https://github.com/thunder-app/markdown-editor.git
      ref: 017c8614c59b7081f54a7af70cc9586888d53b56
  path_provider: ^2.0.15
  logger: ^2.0.2+1
  injectable: ^2.3.2
  freezed_annotation: ^2.4.1
  isar: ^3.0.1
  isar_flutter_libs: ^3.0.1
  dartz: ^0.10.1
  pretty_dio_logger: ^1.3.1
  fading_edge_scrollview: ^3.0.0
  eva_icons_flutter: ^3.1.0
  sliver_tools: ^0.2.12
  cached_network_image: ^3.3.1
  intl: any
  flutter_markdown: ^0.6.18+3
  image_picker: ^1.0.7
  extended_image: ^8.2.0
  share_plus: ^7.2.2
  flutter_localizations:
    sdk: flutter
  gal: ^2.3.0
  permission_handler: ^11.2.1
  device_info_plus: ^9.1.2
  flutter_gen: ^5.4.0
  expandable: ^5.0.1
  jovial_svg: ^1.1.20
  dynamic_color: ^1.6.9
  flex_color_scheme: ^7.3.1
  bloc_concurrency: ^0.2.4
  shared_preferences: ^2.2.2
  stream_transform: ^2.1.0
  l10n_esperanto: ^2.0.8
  flutter_file_dialog: ^3.0.2
  html_unescape: ^2.0.0
  link_preview_generator:
    git:
      url: https://github.com/thunder-app/link_preview_generator.git
      ref: 77a00003216591c32194c2af3c4fc1cf64797e53
  scrollable_positioned_list:
    git:
      url: https://github.com/bitstackapp/flutter.widgets.git
      ref: master
      path: packages/scrollable_positioned_list/
  back_button_interceptor: ^7.0.0
  flutter_typeahead: ^4.6.2
  auto_size_text: ^3.0.0
  flutter_keyboard_visibility: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
